// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : always_latch.mv
// Perintah  : mivon mgen always_latch.mv
// ─────────────────────────────────────────────────────────────


module always_latch_example (
    input  bit clk,
    input  bit rst_n,
    input  bit en,
    input  logic [7:0] d,
    output logic [7:0] q_reg,
    output logic [7:0] q_latch,
    output logic [7:0] q_always
);

    // ── logika sekuensial ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            q_reg <= '0;
        end else if (en) begin
            q_reg <= d;
        end
    end

    // ── always ──
    always begin
        @(posedge clk) q_always = d;
    end

    // ── latch ──
    always_latch begin
        if (en) begin
            q_latch = d;
        end
    end
endmodule

module tb_al (

);
    bit clk, rst_n;
    bit en;
    logic [7:0] d;
    logic [7:0] q_reg;
    logic [7:0] q_latch;
    logic [7:0] q_always;

    always_latch_example u_dut (
        .clk      (clk),
        .rst_n    (rst_n),
        .en       (en),
        .d        (d),
        .q_reg    (q_reg),
        .q_latch  (q_latch),
        .q_always (q_always)
    );

    // ── initial ──
    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end

    // ── initial ──
    initial begin
        rst_n = 0;
        en = 0;
        d = 8'hAA;
        #20 rst_n = 1;
        en = 1;
        d = 8'h55;
        @(posedge clk) begin
            #1 begin
                if (q_reg != 8'h55) begin
                    $error("seq reg failed: %0h", q_reg);
                end
            end
        end
        if (q_always != 8'h55) begin
            $error("always failed: %0h", q_always);
        end
        en = 1;
        d = 8'hBB;
        #1 begin
            if (q_latch != 8'hBB) begin
                $error("latch failed: %0h", q_latch);
            end
        end
        en = 0;
        d = 8'hCC;
        #1 begin
            if (q_latch != 8'hBB) begin
                $error("latch should hold: %0h", q_latch);
            end
        end
        $display("AL_OK reg=%0h latch=%0h always=%0h", q_reg, q_latch, q_always);
        $finish;
    end
endmodule
