// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : array_lit.mv
// Perintah  : mivon mgen array_lit.mv
// ─────────────────────────────────────────────────────────────


module rom_dut (
    input  logic [1:0] idx,
    output logic [7:0] val
);
    logic [7:0] rom [0:3] = '{8'h01, 8'h02, 8'h03, 8'h04};

    // ── logika kombinasional ──
    always_comb begin
        val = rom[idx];
    end
endmodule

module tb_rom;
    logic [1:0] idx;
    logic [7:0] val;

    rom_dut u (
        .idx (idx),
        .val (val)
    );

    // ── initial ──
    initial begin
        idx = 0;
        #1 begin
            if (val == 8'h01) begin
                $display("TB_ROM_OK idx0 val=%0h", val);
            end else begin
                $display("TB_ROM_BROKEN0 val=%0h", val);
            end
        end
        idx = 3;
        #1 $display("TB_ROM idx3 val=%0h", val);
        idx = 1;
        #1 $display("TB_ROM idx1 val=%0h", val);
        $finish;
    end
endmodule
