// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : assume_demo.mv
// Perintah  : mivon mgen assume_demo.mv
// ─────────────────────────────────────────────────────────────


module assume_dut (
    input  bit clk,
    input  bit req,
    output bit ack
);
    assume property (@(posedge clk) req |-> ack);

    // ── logika kombinasional ──
    always_comb begin
        ack = req;
    end
endmodule

module tb_assume;
    bit clk;
    bit req;
    bit ack;

    assume_dut u (
        .clk (clk),
        .req (req),
        .ack (ack)
    );

    // ── initial ──
    initial begin
        clk = 0;
        req = 0;
        #10 assume (req == 0) $info("assume hold"); else $error("assume violated");
        req = 1;
        #10 assert (ack == 1) $info("ack ok"); else $error("ack bad");
        $display("ASSUME_DEMO_OK ack=%0d", ack);
        $finish;
    end

    // ── initial ──
    initial begin
        forever #5 clk = ~clk;
    end
endmodule
