// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : axi_interface.mv
// Perintah  : mivon mgen axi_interface.mv
// ─────────────────────────────────────────────────────────────

`include "axi_interface.svh"

module axi_slave (
    axi_lite axi_if,
    output bit done
);
    logic [3:0] cnt;

    // ── logika sekuensial ──
    always_ff @(posedge axi_if.clk) begin
        if (axi_if.awvalid && axi_if.awready) begin
            cnt <= cnt + 1;
            done <= 1;
        end else begin
            done <= 0;
        end
    end

    // ── logika kombinasional ──
    always_comb begin
        axi_if.awready = axi_if.awvalid;
    end
endmodule

module tb_axi;
    axi_lite bus();
    bit done;

    axi_slave u_slave (
        .axi_if (bus),
        .done   (done)
    );

    // ── initial ──
    initial begin
        while (1) begin
            bus.clk = 0;
            #5 bus.clk = 1;
            #5;
        end
    end

    // ── initial ──
    initial begin
        bus.awaddr = 32'h0000_0010;
        bus.awvalid = 1;
        bus.wdata = 32'hdead_beef;
        bus.wready = 1;
        #40 begin
            if (done) begin
                $display("TB_AXI_OK done=%0d", done);
            end else begin
                $display("TB_AXI_BROKEN done=%0d", done);
            end
        end
        $finish;
    end
endmodule
