// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : bind_check.mv
// Perintah  : mivon mgen bind_check.mv
// ─────────────────────────────────────────────────────────────


module flag_monitor (
    input  bit clk,
    input  bit flag
);

    // ── initial ──
    initial begin
        @(posedge clk) #1 assert (flag == 1) $info("bind sees flag=1"); else $error("bind fail");
        $display("BIND_OK flag=%0d", flag);
    end
endmodule

module dut (
    input  bit clk,
    output bit flag
);

    // ── logika sekuensial ──
    always_ff @(posedge clk) begin
        flag <= 1;
    end
endmodule

module tb_mon;
    bit clk;
    bit flag;

    dut u_dut (
        .clk  (clk),
        .flag (flag)
    );

    bind u_dut flag_monitor u_mon (
        .clk  (clk),
        .flag (flag)
    );

    // ── initial ──
    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end

    // ── initial ──
    initial begin
        #30 $finish;
    end
endmodule
