// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : case_qualifiers.mv
// Perintah  : mivon mgen case_qualifiers.mv
// ─────────────────────────────────────────────────────────────


module case_qualifiers (
    input  bit clk,
    input  bit rst_n,
    input  logic [2:0] sel,
    input  logic [7:0] data_in,
    output logic [7:0] result
);

    // ── logika sekuensial ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            result <= '0;
        end else begin
            priority case (sel)
                3'b1??: begin
                    result <= data_in;
                end
                3'b01?: begin
                    result <= data_in + 1;
                end
                3'b001: begin
                    result <= data_in + 2;
                end
                default: begin
                    result <= '0;
                end
            endcase
        end
    end
endmodule

module tb_caseq (

);
    bit clk, rst_n;
    logic [2:0] sel;
    logic [7:0] data_in;
    logic [7:0] result;

    case_qualifiers u_dut (
        .clk     (clk),
        .rst_n   (rst_n),
        .sel     (sel),
        .data_in (data_in),
        .result  (result)
    );

    // ── initial ──
    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end

    // ── initial ──
    initial begin
        rst_n = 0;
        sel = 0;
        data_in = 8'h10;
        #20 rst_n = 1;
        sel = 3'b101;
        @(posedge clk) begin
            #1 begin
                if (result != 8'h10) begin
                    $error("priority case failed: result=%0h", result);
                end
            end
        end
        sel = 3'b011;
        @(posedge clk) begin
            #1 begin
                if (result != 8'h11) begin
                    $error("priority case arm2 failed: result=%0h", result);
                end
            end
        end
        sel = 3'b001;
        @(posedge clk) begin
            #1 begin
                if (result != 8'h12) begin
                    $error("priority case arm3 failed: result=%0h", result);
                end
            end
        end
        sel = 3'b000;
        @(posedge clk) begin
            #1 begin
                if (result != 8'h00) begin
                    $error("priority case default failed: result=%0h", result);
                end
            end
        end
        $display("CASEQ_OK result=%0h", result);
        $finish;
    end
endmodule
