// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : case_inside.mv
// Perintah  : mivon mgen case_inside.mv
// ─────────────────────────────────────────────────────────────


module ci_dut (
    input  logic [7:0] sel,
    output logic [7:0] y
);

    // ── logika kombinasional ──
    always_comb begin
        case (sel) inside
            0: begin
                y = 8'h00;
            end
            [1:10]: begin
                y = 8'h0A;
            end
            [11:20], 30: begin
                y = 8'h14;
            end
            default: begin
                y = 8'hFF;
            end
        endcase
    end
endmodule

module tb_ci;
    logic [7:0] sel;
    logic [7:0] y;

    ci_dut u (
        .sel (sel),
        .y   (y)
    );

    // ── initial ──
    initial begin
        sel = 0;
        #1 assert (y == 8'h00) $info("v0 ok"); else $error("v0 bad");
        sel = 5;
        #1 assert (y == 8'h0A) $info("range ok"); else $error("range bad");
        sel = 30;
        #1 assert (y == 8'h14) $info("multi ok"); else $error("multi bad");
        sel = 99;
        #1 assert (y == 8'hFF) $info("def ok"); else $error("def bad");
        $display("CASE_INSIDE_OK y=%0h", y);
        $finish;
    end
endmodule
