// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : cast.mv
// Perintah  : mivon mgen cast.mv
// ─────────────────────────────────────────────────────────────

`include "cast.svh"

module cast_dut (
    input  logic [15:0] a,
    output Word16 w,
    output logic [7:0] lo,
    output bit b
);

    // ── logika kombinasional ──
    always_comb begin
        w = Word16'(a);
        lo = logic'(a) ? 8'hAA : 8'h55;
        b = bit'(a[0]);
    end
endmodule

module tb_cast;
    logic [15:0] a;
    Word16 w;
    logic [7:0] lo;
    bit b;

    cast_dut u (
        .a  (a),
        .w  (w),
        .lo (lo),
        .b  (b)
    );

    // ── initial ──
    initial begin
        a = 16'h1234;
        #10 begin
            if (w == 16'h1234 && lo == 8'h55 && b == 0) begin
                $display("TB_CAST_OK w=%0h lo=%0h b=%0d", w, lo, b);
            end else begin
                $display("TB_CAST_BROKEN w=%0h lo=%0h b=%0d", w, lo, b);
            end
        end
        $finish;
    end
endmodule
