// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : compound.mv
// Perintah  : mivon mgen compound.mv
// ─────────────────────────────────────────────────────────────


module tb_ca (

);
    logic [7:0] a;
    logic [7:0] b;
    logic [7:0] c;
    logic [7:0] i;

    // ── initial ──
    initial begin
        a = 10;
        a += 5;
        b = 2;
        b <<= 3;
        c = 8'hFF;
        c &= 8'h0F;
        i = 0;
        i++;
        $display("TB_CA a=%0d b=%0d c=%0d i=%0d", a, b, c, i);
    end
endmodule
