// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : counter.mv
// Perintah  : mivon mgen counter.mv
// ─────────────────────────────────────────────────────────────

`include "counter.svh"
import counter_pkg::*;

module counter #(
    parameter WIDTH = 8,
    parameter MOD = 100
) (
    input  bit clk,
    input  bit rst_n,
    input  bit enable,
    output logic [WIDTH - 1:0] count,
    output Packet packet
);

    // ── logika sekuensial ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            count <= '0;
        end else if (enable) begin
            count <= (count == MOD - 1) ? '0 : count + 1;
        end
    end

    // ── logika kombinasional ──
    always_comb begin
        packet.valid = enable;
        packet.addr = count;
        packet.data = 32'd0;
    end
endmodule
