// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : cover_demo.mv
// Perintah  : mivon mgen cover_demo.mv
// ─────────────────────────────────────────────────────────────


module cov_dut (
    input  bit clk,
    input  bit req,
    output bit ack
);
    cover property (@(posedge clk) req |-> ack);

    // ── logika kombinasional ──
    always_comb begin
        ack = req;
    end
endmodule

module tb_cov;
    bit clk;
    bit req;
    bit ack;

    cov_dut u (
        .clk (clk),
        .req (req),
        .ack (ack)
    );

    // ── initial ──
    initial begin
        clk = 0;
        req = 0;
        #10 req = 1;
        #10 cover (ack == 1) $info("covered ack=1");
        assert (ack == 1) $info("ack ok"); else $error("ack bad");
        $display("COVER_DEMO_OK ack=%0d", ack);
        $finish;
    end

    // ── initial ──
    initial begin
        forever #5 clk = ~clk;
    end
endmodule
