// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : cover.mv
// Perintah  : mivon mgen cover.mv
// ─────────────────────────────────────────────────────────────


module tb_cvg;
    bit clk;
    logic [7:0] x;

    covergroup cg @(posedge clk);
        x: coverpoint x {
            bins lo = {0, 1};
            bins hi = {[2:10]};
        }
    endgroup

    // ── initial ──
    initial begin
        clk = 0;
        x = 0;
        #12 x = 5;
        repeat (10) @(posedge clk) $finish;
    end

    // ── initial ──
    initial begin
        forever #5 clk = ~clk;
    end
endmodule
