// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : disable_label.mv
// Perintah  : mivon mgen disable_label.mv
// ─────────────────────────────────────────────────────────────


module tb_dl;
    logic [7:0] a = '0;
    bit done = 0;

    // ── initial ──
    initial begin
        fork
            begin
                begin : worker
                    #10 a = 1;
                end
            end
            begin
                #5 disable worker;
            end
        join
        done = 1;
        $display("F47_DISABLE_LABEL a=%0d done=%0d", a, done);
        $finish;
    end
endmodule
