// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : dowhile.mv
// Perintah  : mivon mgen dowhile.mv
// ─────────────────────────────────────────────────────────────


module tb_dw (

);
    logic [7:0] i;
    bit ev;
    logic [7:0] got;

    // ── initial ──
    initial begin
        i = 0;
        do begin
            i = i + 1;
        end while (i < 3);
        $display("DW i=%0d", i);
        #10 $finish;
    end

    // ── initial ──
    initial begin
        @(posedge ev) got = 99;
    end

    // ── initial ──
    initial begin
        #5 -> ev;
        #5 $display("EV got=%0d", got);
        $finish;
    end
endmodule
