// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : dsl_demo.mv
// Perintah  : mivon mgen dsl_demo.mv
// ─────────────────────────────────────────────────────────────

`include "dsl_demo.svh"
import dsl_pkg::*;

module dsl_dut (
    input  bit clk,
    input  bit rst_n,
    output State state = IDLE,
    output Word tick = 16'h0,
    output logic [7:0] lo,
    output logic [7:0] hi
);
    logic [7:0] mat [0:1] [0:1] = '{{8'd1, 8'd2}, {8'd3, 8'd4}};

generate
    for (genvar i = 0; i < 2; i = i + 1) begin : gen_i
        always_comb begin
            hi = mat[i][1];
        end
    end
endgenerate

generate
    for (genvar i = 0; i < 2; i = i + 1) begin : gen_i_1
        always_comb begin
            lo = mat[i][0];
        end
    end
endgenerate

    // ── logika sekuensial ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state <= IDLE;
            tick <= 16'h0;
        end else begin
            case (state)
                IDLE: begin
                    state <= WARM;
                    tick <= tick + 16'd1;
                end
                WARM: begin
                    state <= HOT;
                    tick <= tick + 16'd2;
                end
                HOT: begin
                    state <= IDLE;
                    tick <= tick + 16'd3;
                end
            endcase
        end
    end
endmodule

module tb_dsl;
    bit clk, rst_n;
    State state;
    Word tick;
    logic [7:0] lo, hi;
    bit flag;
    int got;
    logic [7:0] hist[$];

    dsl_dut dut (
        .clk   (clk),
        .rst_n (rst_n),
        .state (state),
        .tick  (tick),
        .lo    (lo),
        .hi    (hi)
    );
    logic [7:0] w = 8'd5;

    // ── initial ──
    initial begin
        clk = 0;
        rst_n = 0;
        forever #5 clk = ~clk;
    end

    // ── initial ──
    initial begin
        #20 rst_n = 1;
        repeat (6) @(posedge clk) ;
        @(negedge clk) got = tick;
        force w = 8'd99;
        #1 assert (w == 99) $info("dsl: override aktif"); else $error("dsl: override gagal");
        release w;
        w = 8'd7;
        #1 assert (w == 7) $info("dsl: restore aktif"); else $error("dsl: restore gagal");
        assert (dut.lo == 8'd3) $info("dsl: mat[1][0] benar"); else $error("dsl: mat salah");
        assert (dut.hi == 8'd4) $info("dsl: mat[1][1] benar"); else $error("dsl: mat salah");
        -> flag;
        #1 wait fork;
        disable fork;
        assert (got == 12) $info("dsl: tick benar"); else $error("dsl: tick salah");
        $display("DSL_DEMO_OK tick=%0d lo=%0d hi=%0d w=%0d", got, lo, hi, w);
        $finish;
    end

    // ── initial ──
    initial begin
        @(posedge flag) $display("DSL_DEMO flag terpicu");
    end
endmodule
