// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : dsl_demo.mv
// Perintah  : mivon mgen dsl_demo.mv
// ─────────────────────────────────────────────────────────────

`ifndef DSL_DEMO_SVH
`define DSL_DEMO_SVH

package dsl_pkg;
    localparam TICK_W = 4;
    typedef enum logic [1:0] { IDLE, WARM, HOT } State;
    typedef logic [15:0] Word;
endpackage

`endif
