// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : escape_hatch.mv
// Perintah  : mivon mgen escape_hatch.mv
// ─────────────────────────────────────────────────────────────


module escape_dut (
    input  bit clk,
    input  bit rst_n,
    input  bit inc,
    output logic [7:0] count = '0
);

    // ── logika sekuensial ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            count <= '0;
        end else if (inc) begin
            count <= count + 1;
        end
    end
endmodule

module tb_escape;
    bit clk, rst_n;
    bit inc;
    logic [7:0] count;

    escape_dut u_dut (
        .clk   (clk),
        .rst_n (rst_n),
        .inc   (inc),
        .count (count)
    );
    assert property (@(posedge clk) disable iff (rst_n == 0) inc |-> $past(count) + 1'b1 == count);

    // ── initial ──
    initial begin

                    // $display prosedural sekali (isi @sv bebas menulis `;`)
                    $display("ESCAPE_SVH_DISPLAY t=%0t", $time);

        clk = 0;
        rst_n = 0;
        inc = 0;
        #30 rst_n = 1;
        inc = 1;
        repeat (5) @(posedge clk) $display("TB_ESCAPE_OK count=%0d", count);
        $finish;
    end

    // ── initial ──
    initial begin
        forever #5 clk = ~clk;
    end
endmodule
