// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : features_new.mv
// Perintah  : mivon mgen features_new.mv
// ─────────────────────────────────────────────────────────────

typedef logic [7:0] Word8;
typedef enum logic [1:0] { OFF, ON } Mode;

module fn_dut (
    output Word8 val,
    output Mode m
);
    logic [7:0] rom [0:3];

    // ── initial ──
    initial begin
        foreach (rom[i]) begin
            rom[i] = i;
        end
    end

    // ── logika kombinasional ──
    always_comb begin
        val = scale(10, .factor(3));
        m = ON;
    end
endmodule

module tb_fn;
    logic [7:0] val;
    logic [0:0] m;

    fn_dut u (
        .val (val),
        .m   (m)
    );

    // ── initial ──
    initial begin
        #2 begin
            if (val == 8'h1E && m == 1) begin
                $display("TB_FN_OK val=%0d m=%0d", val, m);
            end else begin
                $display("TB_FN_BROKEN val=%0d m=%0d", val, m);
            end
        end
        $finish;
    end
endmodule

function int scale(input int v, input int factor = 4);
    return v * factor;
endfunction
