// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : fib.mv
// Perintah  : mivon mgen fib.mv
// ─────────────────────────────────────────────────────────────


module tb_fib;
    logic [31:0] o_fib;
    logic [31:0] o_fact;

    // ── initial ──
    initial begin
        o_fib = fib(15);
        o_fact = factorial(5);
        #1 $display("TB_FIB fib=%0d fact=%0d", o_fib, o_fact);
    end
endmodule

function int fib(input int n);
    if (n <= 1) begin
        return n;
    end
    return fib(n - 1) + fib(n - 2);
endfunction

function int factorial(input int n);
    if (n <= 1) begin
        return 1;
    end
    return n * factorial(n - 1);
endfunction
