// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : for_step.mv
// Perintah  : mivon mgen for_step.mv
// ─────────────────────────────────────────────────────────────


module step_dut (
    input  bit clk,
    output logic [7:0] y
);

    // ── logika kombinasional ──
    always_comb begin
        y = 8'h00;
        for (int i = 0; i < 7; i = i + 2) begin
            y[i] = 1'b1;
        end
    end
endmodule

module tb_step;
    bit clk;
    logic [7:0] y;

    step_dut u (
        .clk (clk),
        .y   (y)
    );

    // ── initial ──
    initial begin
        clk = 0;
        #10 begin
            if (y == 8'h55) begin
                $display("TB_STEP_OK y=%0h", y);
            end else begin
                $display("TB_STEP_BROKEN y=%0h", y);
            end
        end
        $finish;
    end
endmodule
