// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : force_release.mv
// Perintah  : mivon mgen force_release.mv
// ─────────────────────────────────────────────────────────────


module tb_fr;
    logic [7:0] w = '0;
task poke();
    force w = 99;
    #5 $display("FR_MID w=%0d", w);
    release w;
    w = 7;
endtask

    // ── initial ──
    initial begin
        w = 42;
        #1 force w = 77;
        w = 1;
        #1 $display("FR_FORCED w=%0d", w);
        release w;
        w = 5;
        #1 $display("FR_UNBLOCKED w=%0d", w);
    end

    // ── initial ──
    initial begin
        #10 poke();
        #1 begin
            if (w == 7) begin
                $display("FR_OK w=%0d", w);
            end else begin
                $display("FR_FAIL w=%0d", w);
            end
        end
        $finish;
    end
endmodule
