// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : forkjoin.mv
// Perintah  : mivon mgen forkjoin.mv
// ─────────────────────────────────────────────────────────────


module tb_fj (
    input  bit clk
);
    logic [7:0] ja, jb;

    // ── initial ──
    initial begin
        fork
            begin
                #10 ja = 1;
            end
            begin
                #5 jb = 2;
            end
        join
        #1 $display("FJ_JOIN ja=%0d jb=%0d", ja, jb);
    end
    logic [7:0] aa, ab;

    // ── initial ──
    initial begin
        fork
            begin
                #10 aa = 11;
            end
            begin
                #5 ab = 12;
            end
        join_any
        #1 $display("FJ_ANY0 aa=%0d ab=%0d", aa, ab);
        #10 $display("FJ_ANY1 aa=%0d ab=%0d", aa, ab);
    end
    logic [7:0] nb;

    // ── initial ──
    initial begin
        fork
            begin
                #10 nb = 22;
            end
        join_none
        $display("FJ_NONE0 nb=%0d", nb);
        #15 $display("FJ_NONE1 nb=%0d", nb);
        #1 $finish;
    end
endmodule
