// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : fork_ctrl.mv
// Perintah  : mivon mgen fork_ctrl.mv
// ─────────────────────────────────────────────────────────────


module tb_fc;
    logic [7:0] a = '0;
    logic [7:0] b = '0;
    logic [7:0] c = '0;

    // ── initial ──
    initial begin
        fork
            begin
                #10 a = 1;
            end
            begin
                #5 b = 2;
            end
        join_none
        wait fork;
        $display("WAIT_FORK_DONE a=%0d b=%0d", a, b);
    end

    // ── initial ──
    initial begin
        fork
            begin
                #10 c = 99;
            end
        join_none
        #2 disable fork;
        #15 $display("DISABLE_FORK c=%0d", c);
        $finish;
    end
endmodule
