// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : func_local.mv
// Perintah  : mivon mgen func_local.mv
// ─────────────────────────────────────────────────────────────


module func_dut (
    input  logic [15:0] a,
    output logic [3:0] o,
    output logic [15:0] s
);

    // ── logika kombinasional ──
    always_comb begin
        o = clog2(a);
        s = scale(a[7:0]);
    end
endmodule

module tb_fl;
    logic [15:0] a;
    logic [3:0] o;
    logic [15:0] s;

    func_dut u (
        .a (a),
        .o (o),
        .s (s)
    );

    // ── initial ──
    initial begin
        a = 16'h0100;
        #1 $display("TB_FL o=%0d s=%0d", o, s);
    end
endmodule

function int clog2(input int x);
    int r = 0;
    int n = x - 1;
    while (n > 0) begin
        r = r + 1;
        n = n >> 1;
    end
    return r;
endfunction

function int scale(input int v);
    int w = v * 2;
    return w;
endfunction
