// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : gen_case.mv
// Perintah  : mivon mgen gen_case.mv
// ─────────────────────────────────────────────────────────────


module gc_demo #(
    parameter SEL = 1
) (
    input  bit clk,
    output logic [7:0] y
);

generate
    case (SEL)
    0: begin : gen_case
        always_comb begin
            y = 8'd10;
        end
    end
    1, 2: begin : gen_case_1
        always_comb begin
            y = 8'd20;
        end
    end
    default: begin : gen_case_else
        always_comb begin
            y = 8'd99;
        end
    end
    endcase
endgenerate
endmodule

module tb_gc;
    bit clk;
    logic [7:0] y;

    gc_demo u (
        .clk (clk),
        .y   (y)
    );

    // ── initial ──
    initial begin
        clk = 0;
        #1 assert (y == 20) $info("sel1 ok"); else $error("sel1 fail");
        $display("GC_OK y=%0d", y);
        $finish;
    end
endmodule
