// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : multidim.mv
// Perintah  : mivon mgen multidim.mv
// ─────────────────────────────────────────────────────────────


module tb_md (
    input  bit clk,
    output logic [7:0] m00,
    output logic [7:0] m11,
    output logic [7:0] mi
);
    logic [7:0] mat [0:1] [0:1] = '{{1, 2}, {3, 4}};

    // ── logika kombinasional ──
    always_comb begin
        m00 = mat[0][0];
        m11 = mat[1][1];
        mi = mat[1][0];
    end

    // ── initial ──
    initial begin
        #1 assert (m00 == 1 && m11 == 4 && mi == 3) $info("MD_OK m00=%0d m11=%0d", m00, m11); else $error("MD multi-dim gagal");
    end
endmodule
