// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : nets.mv
// Perintah  : mivon mgen nets.mv
// ─────────────────────────────────────────────────────────────


module nets_demo (
    input  bit a,
    output bit o_and,
    output bit o_or
);
    wand w_and;
    wor w_or;
    tri tr;
    tri0 t0;
    tri1 t1;
    supply0 s0;
    supply1 s1;
    assign w_and = a;
    assign w_and = 0;
    assign w_or = a;
    assign w_or = 0;
    assign tr = a;
    assign t0 = 1'bz;
    assign t1 = 1'bz;
    assign o_and = w_and & s1 & tr;
    assign o_or = w_or | s0 | tr;
endmodule

module tb_nets;
    bit a;
    bit o_and;
    bit o_or;

    nets_demo u (
        .a     (a),
        .o_and (o_and),
        .o_or  (o_or)
    );

    // ── initial ──
    initial begin
        a = 1;
        #1 assert (o_and == 0) $info("wand ok"); else $error("wand fail");
        assert (o_or == 1) $info("wor ok"); else $error("wor fail");
        $display("NETS_OK and=%0d or=%0d", o_and, o_or);
        $finish;
    end
endmodule
