// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : prefix_incdec.mv
// Perintah  : mivon mgen prefix_incdec.mv
// ─────────────────────────────────────────────────────────────


module tb_pp;
    logic [7:0] i;
    logic [7:0] j;

    // ── initial ──
    initial begin
        i = 0;
        ++i;
        $display("PP_A i=%0d", i);
        j = ++i;
        $display("PP_B i=%0d j=%0d", i, j);
        --i;
        $display("PP_C i=%0d", i);
        i--;
        $display("PP_D i=%0d", i);
        $finish;
    end
endmodule
