// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : queue.mv
// Perintah  : mivon mgen queue.mv
// ─────────────────────────────────────────────────────────────


module tb_queue (

);
    logic [7:0] q[$];
    logic [7:0] sum = 0;

    // ── initial ──
    initial begin
        q.push_back(8'd3);
        q.push_back(8'd4);
        $display("Q size=%0d first=%0d last=%0d", q.size(), q[0], q[1]);
        q.push_front(8'd1);
        $display("FRONT size=%0d first=%0d", q.size(), q[0]);
        sum = 0;
        for (int i = 0; i < 3; i = i + 1) begin
            sum += q[i];
        end
        $display("SCAN n=%0d sum=%0d", q.size(), sum);
        sum = q.pop_front();
        sum = q.pop_front();
        sum = q.pop_front();
        $display("POP size=%0d", q.size());
        q.delete();
        $display("CLEARED size=%0d", q.size());
        $finish;
    end
endmodule
