// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : tb_counter.mv
// Perintah  : mivon mgen tb_counter.mv
// ─────────────────────────────────────────────────────────────


module counter_dut #(
    parameter WIDTH = 8
) (
    input  bit clk,
    input  bit rst_n,
    input  bit enable,
    output logic [WIDTH - 1:0] count
);

    // ── logika sekuensial ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            count <= '0;
        end else if (enable) begin
            count <= count + 1;
        end
    end
endmodule

module tb_counter;
    bit clk, rst_n;
    bit enable;
    logic [7:0] count;

    counter_dut u_counter (
        .clk    (clk),
        .rst_n  (rst_n),
        .enable (enable),
        .count  (count)
    );

    // ── initial ──
    initial begin
        $display("tb_counter: mulai");
        clk = 0;
        rst_n = 0;
        enable = 0;
        #20 rst_n = 1;
        enable = 1;
        repeat (300) @(posedge clk) $finish;
    end

    // ── initial ──
    initial begin
        forever #5 clk = ~clk;
    end

    // ── initial ──
    initial begin
        #40 assert (count > 0) $info("counter ok"); else $fatal("counter stuck");
    end
    assert property (@(posedge clk) count === count);
endmodule
