// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : traffic.mv
// Perintah  : mivon mgen traffic.mv
// ─────────────────────────────────────────────────────────────

`include "traffic.svh"
import traffic_pkg::*;

module traffic #(
    parameter GREEN_T = 30,
    parameter YELLOW_T = 5
) (
    input  bit clk,
    input  bit rst_n,
    output State state,
    output bit red,
    output bit green,
    output bit yellow
);
    logic [7:0] timer;

    // ── logika sekuensial ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state <= RED;
            timer <= 0;
        end else begin
            case (state)
                RED: begin
                    if (timer == GREEN_T) begin
                        state <= GREEN;
                        timer <= 0;
                    end else begin
                        timer <= timer + 1;
                    end
                end
                GREEN: begin
                    if (timer == YELLOW_T) begin
                        state <= YELLOW;
                        timer <= 0;
                    end else begin
                        timer <= timer + 1;
                    end
                end
                YELLOW: begin
                    state <= RED;
                    timer <= 0;
                end
            endcase
        end
    end

    // ── logika kombinasional ──
    always_comb begin
        red = (state == RED);
        green = (state == GREEN);
        yellow = (state == YELLOW);
    end
endmodule
