// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : type_param.mv
// Perintah  : mivon mgen type_param.mv
// ─────────────────────────────────────────────────────────────

`ifndef TYPE_PARAM_SVH
`define TYPE_PARAM_SVH

typedef logic [15:0] Wide16;

`endif
