// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : type_param.mv
// Perintah  : mivon mgen type_param.mv
// ─────────────────────────────────────────────────────────────

`include "type_param.svh"

module shifter #(
    parameter type T = logic [7:0],
    parameter N = 2
) (
    input  bit clk,
    input  T d,
    output T q
);
    T r;

    // ── logika sekuensial ──
    always_ff @(posedge clk) begin
        r <= d << N;
        q <= r;
    end
endmodule

module tb_tp (

);
    bit clk;
    logic [7:0] d8, q8;
    logic [15:0] d16, q16;

    shifter u8 (
        .clk (clk),
        .d   (d8),
        .q   (q8)
    );

    shifter u16 #(.T(Word16), .N(3)) (
        .clk (clk),
        .d   (d16),
        .q   (q16)
    );

    // ── initial ──
    initial begin
        clk = 0;
        d8 = 8'h01;
        d16 = 16'h0001;
        #10 begin
            repeat (3) @(posedge clk) ;
        end
        #1 begin
            if (q8 == 8'h04 && q16 == 16'h0008) begin
                $display("TB_TP_OK q8=%0d q16=%0d", q8, q16);
            end else begin
                $display("TB_TP_BROKEN q8=%0d q16=%0d", q8, q16);
            end
        end
        $finish;
    end

    // ── initial ──
    initial begin
        forever #5 clk = ~clk;
    end
endmodule
