// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : unique_if.mv
// Perintah  : mivon mgen unique_if.mv
// ─────────────────────────────────────────────────────────────


module ui_dut (
    input  bit a,
    input  bit b,
    output logic [1:0] y
);

    // ── logika kombinasional ──
    always_comb begin
        unique if (a) begin
            y = 1;
        end else if (b) begin
            y = 2;
        end else begin
            y = 0;
        end
    end
endmodule

module tb_ui;
    bit a;
    bit b;
    logic [1:0] y;

    ui_dut u (
        .a (a),
        .b (b),
        .y (y)
    );

    // ── initial ──
    initial begin
        a = 1;
        b = 1;
        #1 assert (y == 1) $info("unique-a ok"); else $error("unique-a bad");
        a = 0;
        #1 assert (y == 2) $info("elseif-b ok"); else $error("elseif-b bad");
        b = 0;
        #1 assert (y == 0) $info("else ok"); else $error("else bad");
        $display("UNIQUE_IF_OK y=%0d", y);
        $finish;
    end
endmodule
