// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : wait_example.mv
// Perintah  : mivon mgen wait_example.mv
// ─────────────────────────────────────────────────────────────


module wait_example (
    input  bit clk,
    input  bit rst_n,
    output bit done = 0,
    output logic [7:0] data = '0
);

    // ── logika sekuensial ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            done <= 0;
            data <= '0;
        end else begin
            done <= 1;
            data <= 8'h42;
        end
    end
endmodule

module tb_wait;
    bit clk, rst_n;
    bit done;
    logic [7:0] data;
    logic [7:0] got;

    wait_example u_dut (
        .clk   (clk),
        .rst_n (rst_n),
        .done  (done),
        .data  (data)
    );

    // ── initial ──
    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end

    // ── initial ──
    initial begin
        rst_n = 0;
        #20 rst_n = 1;
        wait (done == 1) begin
            got = data;
        end
        if (got != 8'h42) begin
            $error("wait failed: got=%0h", got);
        end
        $display("WAIT_OK got=%0h", got);
        $finish;
    end
endmodule
