// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : wire_assign.mv
// Perintah  : mivon mgen wire_assign.mv
// ─────────────────────────────────────────────────────────────


module wire_alu (
    input  bit a,
    input  bit b,
    input  logic [7:0] x,
    output bit y,
    output logic [7:0] v
);
    wire w_and;
    wire w_or;
    wire [7:0] wv;
    assign w_and = a & b;
    assign w_or = a | b;
    assign y = w_and ^ w_or;
    assign wv = x + 1;
    assign v = wv;
endmodule

module tb_wire;
    bit a, b;
    logic [7:0] x;
    bit y;
    logic [7:0] v;

    wire_alu u (
        .a (a),
        .b (b),
        .x (x),
        .y (y),
        .v (v)
    );

    // ── initial ──
    initial begin
        a = 0;
        b = 0;
        x = 41;
        #1 assert (y == 0) $info("c0 ok"); else $error("c0 fail");
        assert (v == 42) $info("v ok"); else $error("v fail");
        a = 1;
        b = 1;
        #1 assert (y == 0) $info("c1 ok"); else $error("c1 fail");
        a = 1;
        b = 0;
        #1 assert (y == 1) $info("c2 ok"); else $error("c2 fail");
        $display("WIRE_ASSIGN_OK y=%0d v=%0d", y, v);
        $finish;
    end
endmodule
