//! Mivon HDL (.mv) — Codegen. Emitter SystemVerilog: AST → `.sv` + `.svh`.
//! 1 file = 1 tanggung jawab. Struktur (berkembang):
//! - `mod.rs`   — entry generate/generate_with_ifaces, header, .svh (package/
//!   typedef/interface), .sv skeleton, helpers dasar
//! - `module.rs`— module/program/port/signal/reg/const/seq/comb/always/latch/
//!   initial/final/inst/generate/func/task
//! - `stmt.rs`  — statement emitter + single-line compaction + @sv raw
//! - `expr.rs`  — ekspresi SV + tipe (emit_type/emit_expr)
//! - `defs.rs`  — emit_typedef/emit_package/emit_interface/emit_class
//! - `tests.rs` — unit test

use crate::ast::*;

pub mod defs;
pub mod expr;
pub mod module;
pub mod stmt;

#[cfg(test)]
mod tests;

/// Hasil codegen: (sv, svh).
#[derive(Debug, Clone)]
pub struct GenOutput {
    pub sv: String,
    pub svh: String,
}

/// Generate `.sv` + `.svh` dari `MvFile` (konteks satu file).
pub fn generate(file: &MvFile, base: &str) -> GenOutput {
    let ifaces: Vec<&str> = file.interfaces.iter().map(|i| i.name.as_str()).collect();
    generate_src_ext(file, base, &ifaces, "mv")
}

/// Generate dgn nama interface dari KONTEKS GABUNGAN (F26): port module
/// bertipe interface yang didefinisikan di FILE LAIN juga di-emit tanpa
/// arah (`bus b`) — konsisten dengan `check_many` yang memakai konteks
/// gabungan. `generate` (satu file) memanggil ini dgn daftar sendiri.
/// Ekstensi sumber default `.mv` — pemanggil yang tahu ekstensi asli
/// (`.mvh`, F43) pakai `generate_src_ext`.
pub fn generate_with_ifaces(file: &MvFile, base: &str, iface_names: &[&str]) -> GenOutput {
    generate_src_ext(file, base, iface_names, "mv")
}

/// Generate dgn ekstensi sumber eksplisit (`mv`/`mvh`) — header komentar
/// `Sumber:`/`Perintah:` menampilkan nama file asli yang benar (F43).
/// Untuk sumber `.mvh`, `sv` tetap dihasilkan hanya bila file memuat
/// konten fungsional (kontrak: `.mvh` validasi header-only di check).
pub fn generate_src_ext(
    file: &MvFile,
    base: &str,
    iface_names: &[&str],
    src_ext: &str,
) -> GenOutput {
    let header = header(base, src_ext);
    let svh = generate_svh(file, base, &header);
    let sv = generate_sv(file, base, &header, iface_names);
    GenOutput { sv, svh }
}

// ── Header ──

fn header(base: &str, src_ext: &str) -> String {
    let line = "// ─────────────────────────────────────────────────────────────";
    format!(
        "{line}\n// Generated by mivon mgen — DO NOT EDIT\n// Sumber    : {base}.{src_ext}\n// Perintah  : mivon mgen {base}.{src_ext}\n{line}\n"
    )
}

// ── .svh ──

/// Emit `.svh` HANYA jika file punya definisi bersama (package atau typedef
/// level file) yang perlu di-include oleh `.sv`.
fn generate_svh(file: &MvFile, base: &str, header: &str) -> String {
    // Definisi bersama = typedef level file + package + interface (F26).
    let has_shared =
        !file.typedefs.is_empty() || !file.packages.is_empty() || !file.interfaces.is_empty();
    if !has_shared {
        return String::new();
    }
    let guard = format!("{}_SVH", base.to_uppercase());
    let mut out = String::new();
    out.push_str(header);
    out.push('\n');
    out.push_str(&format!("`ifndef {guard}\n`define {guard}\n"));

    for td in &file.typedefs {
        out.push('\n');
        defs::emit_typedef(&mut out, 0, td);
    }
    for pkg in &file.packages {
        out.push('\n');
        defs::emit_package(&mut out, 0, pkg);
    }
    for ifc in &file.interfaces {
        out.push('\n');
        defs::emit_interface(&mut out, 0, ifc);
    }

    out.push('\n');
    out.push_str("`endif\n");
    out
}

// ── .sv ──

fn generate_sv(file: &MvFile, base: &str, header: &str, iface_names: &[&str]) -> String {
    // F30 fix: file yang hanya berisi definisi bersama (package/typedef/
    // interface) tanpa module/program/class/func/task tidak menghasilkan
    // konten fungsional — kembalikan kosong agar `mgen` tidak menulis .sv.
    let has_content = !file.modules.is_empty()
        || !file.programs.is_empty()
        || !file.classes.is_empty()
        || !file.funcs.is_empty()
        || !file.tasks.is_empty();
    if !has_content {
        return String::new();
    }

    let mut out = String::new();
    out.push_str(header);
    out.push('\n');

    let has_shared =
        !file.typedefs.is_empty() || !file.packages.is_empty() || !file.interfaces.is_empty();
    if has_shared {
        out.push_str(&format!("`include \"{base}.svh\"\n"));
    }

    for m in &file.modules {
        out.push('\n');
        module::emit_module_kw(&mut out, m, "module", iface_names);
    }
    // `program name { ... }` (MIVON-HDL.md §7.3) — testbench program
    for p in &file.programs {
        out.push('\n');
        module::emit_module_kw(&mut out, p, "program", iface_names);
    }
    for c in &file.classes {
        out.push('\n');
        defs::emit_class(&mut out, c);
    }
    for f in &file.funcs {
        out.push('\n');
        module::emit_func(&mut out, f);
    }
    for t in &file.tasks {
        out.push('\n');
        module::emit_task(&mut out, t);
    }
    out
}

// ── Helpers ──

pub(crate) fn line(out: &mut String, indent: usize, s: &str) {
    out.push_str(&"    ".repeat(indent));
    out.push_str(s);
    out.push('\n');
}

/// Tipe dengan padding agar kolom nama rapi (minimal 1 spasi).
pub(crate) fn pad_type(t: String) -> String {
    if t.len() < 6 {
        format!("{t}{}", " ".repeat(6 - t.len()))
    } else {
        format!("{t} ")
    }
}

/// Suffix inisialisasi deklarasi: `= expr` bila ada, kosong bila tidak.
pub(crate) fn emit_init(init: &Option<Expr>) -> String {
    init.as_ref()
        .map(|e| format!(" = {}", expr::emit_expr(e)))
        .unwrap_or_default()
}

/// Ekspresi increment loop `for`: `i + 1` (default) atau `i + <step>` bila
/// `step` diberikan (`for i in 0..N step 2`). Pemanggil menulis `{var} = {}`.
pub(crate) fn for_inc(var: &str, step: Option<&Expr>) -> String {
    match step {
        Some(s) => format!("{var} + {}", expr::emit_expr(s)),
        None => format!("{var} + 1"),
    }
}

/// Deklarasi signal multi-nama yang BENAR utk SV: tipe di-emit SEKALI,
/// nama dipisah koma, dims array SETELAH tiap nama:
/// `sig a, b : logic[8][4]` → `logic [7:0] a [0:3], b [0:3]`
/// (sebelumnya `logic [7:0] a [0:3], logic [7:0] b [0:3]` — SV INVALID,
/// tipe berulang per nama). Dipakai deklarasi `sig`/`reg`/`var` multi-nama.
pub(crate) fn emit_signal_decl_multi(ty: &MvType, names: &[String]) -> String {
    // F40: queue membungkus tipe luar — pecah dulu, `[$]` dirender per nama.
    let (ty, is_queue) = match ty {
        MvType::Queue(inner) => (inner.as_ref(), true),
        other => (other, false),
    };
    let mut dims: Vec<&Expr> = Vec::new();
    let mut elem = ty;
    while let MvType::Array(inner, ds) = elem {
        dims.extend(ds.iter());
        elem = inner;
    }
    let ty_s = expr::emit_type(elem);
    let name_parts: Vec<String> = names
        .iter()
        .map(|n| {
            let mut s = n.clone();
            for d in &dims {
                let nn = match d {
                    Expr::Int(v) => format!("{}", v.saturating_sub(1)),
                    other => format!("{} - 1", expr::emit_expr(other)),
                };
                s.push_str(&format!(" [0:{nn}]"));
            }
            if is_queue {
                s.push_str("[$]");
            }
            s
        })
        .collect();
    format!("{ty_s} {}", name_parts.join(", "))
}

/// Deklarasi signal array unpacked yang BENAR utk SV:
/// `logic[8][4]` → `logic [7:0] name [0:3]` (dims `[0:N-1]` SETELAH nama,
/// bukan `logic [7:0] [4] name` yang di-parse SV sbg packed multi-dim).
pub(crate) fn emit_signal_decl(ty: &MvType, name: &str) -> String {
    // F40: queue — `[$]` SETELAH nama (bukan setelah tipe).
    let (ty, is_queue) = match ty {
        MvType::Queue(inner) => (inner.as_ref(), true),
        other => (other, false),
    };
    let mut dims: Vec<&Expr> = Vec::new();
    let mut elem = ty;
    while let MvType::Array(inner, ds) = elem {
        dims.extend(ds.iter());
        elem = inner;
    }
    let mut s = format!("{} {name}", expr::emit_type(elem));
    for d in dims {
        let n = match d {
            Expr::Int(v) => format!("{}", v.saturating_sub(1)),
            other => format!("{} - 1", expr::emit_expr(other)),
        };
        s.push_str(&format!(" [0:{n}]"));
    }
    if is_queue {
        s.push_str("[$]");
    }
    s
}
