//! Mivon HDL (.mv) — Codegen. Emitter SystemVerilog: AST → `.sv` + `.svh`.
//! 1 file = 1 tanggung jawab. Struktur (berkembang):
//! - `mod.rs`   — entry generate/generate_with_ifaces, header, .svh (package/
//!   typedef/interface), .sv skeleton, helpers dasar
//! - `module.rs`— module/program/port/signal/reg/const/seq/comb/always/latch/
//!   initial/final/inst/generate/func/task
//! - `stmt.rs`  — statement emitter + single-line compaction + @sv raw
//! - `expr.rs`  — ekspresi SV + tipe (emit_type/emit_expr)
//! - `defs.rs`  — emit_typedef/emit_package/emit_interface/emit_class
//! - `tests.rs` — unit test

use crate::ast::*;

pub mod defs;
pub mod expr;
pub mod module;
pub mod stmt;

#[cfg(test)]
mod tests;

/// Hasil codegen: (sv, svh).
#[derive(Debug, Clone)]
pub struct GenOutput {
    pub sv: String,
    pub svh: String,
}

/// Opsi emisi codegen (`mgen --package <nama>`, MIVON-HDL.md §11).
#[derive(Debug, Clone, Default)]
pub struct GenOpts<'a> {
    /// Bungkus typedef level file di dalam `package <nama>; ... endpackage`
    /// di `.svh`; `.sv` yang meng-`include` otomatis dapat
    /// `import <nama>::*;`. Paket yang SUDAH ada di sumber tetap di-emit
    /// apa adanya (nama dari sumber menang).
    pub package: Option<&'a str>,
    /// F77: nama base `.svh` dari file LAIN dalam batch yang definisi
    /// bersamanya (package/typedef/interface) di-refer file ini. Di-emit
    /// `` `include "<base>.svh" `` di scope file SEBELUM `import`/module,
    /// supaya `.sv`/`.svh` hasil generate mandiri di tool EDA (iverilog dan
    /// verilator TIDAK resolve dependensi lintas-file sendiri). Urutan:
    /// include lintas-file dulu, baru include `.svh` file sendiri, agar
    /// package file sendiri yang merujuk tipe file lain sudah melihatnya.
    pub includes: Vec<&'a str>,
}

/// Generate `.sv` + `.svh` dari `MvFile` (konteks satu file).
pub fn generate(file: &MvFile, base: &str) -> GenOutput {
    let ifaces: Vec<&str> = file.interfaces.iter().map(|i| i.name.as_str()).collect();
    generate_src_ext(file, base, &ifaces, "mv")
}

/// Generate dgn nama interface dari KONTEKS GABUNGAN (F26): port module
/// bertipe interface yang didefinisikan di FILE LAIN juga di-emit tanpa
/// arah (`bus b`) — konsisten dengan `check_many` yang memakai konteks
/// gabungan. `generate` (satu file) memanggil ini dgn daftar sendiri.
/// Ekstensi sumber default `.mv` — pemanggil yang tahu ekstensi asli
/// (`.mvh`, F43) pakai `generate_src_ext`.
pub fn generate_with_ifaces(file: &MvFile, base: &str, iface_names: &[&str]) -> GenOutput {
    generate_src_ext(file, base, iface_names, "mv")
}

/// Generate dgn ekstensi sumber eksplisit (`mv`/`mvh`) — header komentar
/// `Sumber:`/`Perintah:` menampilkan nama file asli yang benar (F43).
/// Untuk sumber `.mvh`, `sv` tetap dihasilkan hanya bila file memuat
/// konten fungsional (kontrak: `.mvh` validasi header-only di check).
pub fn generate_src_ext(
    file: &MvFile,
    base: &str,
    iface_names: &[&str],
    src_ext: &str,
) -> GenOutput {
    generate_src_ext_opts(file, base, iface_names, src_ext, &GenOpts::default())
}

/// `generate_src_ext` dengan opsi emisi (`mgen --package`).
pub fn generate_src_ext_opts(
    file: &MvFile,
    base: &str,
    iface_names: &[&str],
    src_ext: &str,
    opts: &GenOpts,
) -> GenOutput {
    let header = header(base, src_ext);
    let svh = generate_svh_opts(file, base, &header, opts);
    let sv = generate_sv_opts(file, base, &header, iface_names, opts);
    GenOutput { sv, svh }
}

// ── Header ──

fn header(base: &str, src_ext: &str) -> String {
    let line = "// ─────────────────────────────────────────────────────────────";
    format!(
        "{line}\n// Generated by mivon mgen — DO NOT EDIT\n// Sumber    : {base}.{src_ext}\n// Perintah  : mivon mgen {base}.{src_ext}\n{line}\n"
    )
}

// ── .svh ──

/// `generate_svh` dengan opsi emisi. `--package <nama>` membungkus typedef
/// level file dalam `package <nama>; ... endpackage` (MIVON-HDL.md §11) —
/// interface/package dari sumber tetap di luar, nama dari sumber menang.
fn generate_svh_opts(file: &MvFile, base: &str, header: &str, opts: &GenOpts) -> String {
    // Definisi bersama = typedef level file + package + interface (F26).
    let has_shared =
        !file.typedefs.is_empty() || !file.packages.is_empty() || !file.interfaces.is_empty();
    if !has_shared {
        return String::new();
    }
    let guard = format!("{}_SVH", base.to_uppercase());
    let mut out = String::new();
    out.push_str(header);
    out.push('\n');
    out.push_str(&format!("`ifndef {guard}\n`define {guard}\n"));

    // F77: definisi bersama dari file LAIN dalam batch (package/typedef/
    // interface yang di-refer file ini) di-`include` lebih dulu, supaya
    // `.svh` mandiri di tool EDA. Guard di file sumber mencegah dobel.
    for inc in &opts.includes {
        out.push_str(&format!("`include \"{inc}.svh\"\n"));
    }
    if !opts.includes.is_empty() {
        out.push('\n');
    }

    // `--package`: typedef level file → di dalam satu package (deterministik,
    // SV valid). Package/interface dari sumber tetap di luar — nama dari
    // sumber menang.
    match opts.package.filter(|_| !file.typedefs.is_empty()) {
        Some(pkg_name) => {
            out.push('\n');
            line(&mut out, 0, &format!("package {pkg_name};"));
            for td in &file.typedefs {
                defs::emit_typedef(&mut out, 1, td);
            }
            line(&mut out, 0, "endpackage");
        }
        None => {
            for td in &file.typedefs {
                out.push('\n');
                defs::emit_typedef(&mut out, 0, td);
            }
        }
    }
    for pkg in &file.packages {
        out.push('\n');
        defs::emit_package(&mut out, 0, pkg);
    }
    for ifc in &file.interfaces {
        out.push('\n');
        defs::emit_interface(&mut out, 0, ifc);
    }

    out.push('\n');
    out.push_str("`endif\n");
    out
}

// ── .sv ──

/// `generate_sv` dengan opsi emisi. `--package <nama>` menambahkan
/// `import <nama>::*;` setelah `` `include `` agar typedef yang kini
/// berada di dalam package tetap terlihat di module ini.
fn generate_sv_opts(
    file: &MvFile,
    base: &str,
    header: &str,
    iface_names: &[&str],
    opts: &GenOpts,
) -> String {
    // F30 fix: file yang hanya berisi definisi bersama (package/typedef/
    // interface) tanpa module/program/class/func/task tidak menghasilkan
    // konten fungsional — kembalikan kosong agar `mgen` tidak menulis .sv.
    let has_content = !file.modules.is_empty()
        || !file.programs.is_empty()
        || !file.classes.is_empty()
        || !file.funcs.is_empty()
        || !file.tasks.is_empty();
    if !has_content {
        return String::new();
    }

    let mut out = String::new();
    out.push_str(header);
    out.push('\n');

    // F77: definisi bersama dari file LAIN dalam batch (package/typedef/
    // interface yang di-refer file ini) di-`include` lebih dulu, supaya
    // `.sv` mandiri di tool EDA (iverilog/verilator tak resolve dependensi
    // lintas-file sendiri). Include `.svh` file sendiri menyusul di bawah.
    for inc in &opts.includes {
        out.push_str(&format!("`include \"{inc}.svh\"\n"));
    }

    let has_shared =
        !file.typedefs.is_empty() || !file.packages.is_empty() || !file.interfaces.is_empty();
    if has_shared {
        out.push_str(&format!("`include \"{base}.svh\"\n"));
        // `--package`: typedef wrapped → module ini butuh import eksplisit.
        if let Some(pkg) = opts.package.filter(|_| !file.typedefs.is_empty()) {
            out.push_str(&format!("import {pkg}::*;\n"));
        }
    }

    // LRM 1800 §26.3 + §23.2.1.2: nama yang dipakai di ANSI port list dan
    // parameter port list di-resolve di scope ENCLOSING (unit kompilasi),
    // BUKAN di dalam body module. `import` yang diletakkan di body module
    // (dananya sudah lalu) tidak membuat tipe package terlihat di port list
    // → `output State state` tak ter-resolve (iverilog/verilator: syntax
    // error). Karena itu `use pkg::*` di-backend SV materialized sebagai
    // `import` di scope FILE, SEBELUM deklarasi module. Sifat import file-scope
    // sedikit lebih luas dari `use` per-module, tapi itu aman: checker
    // (E2005) sudah menolak tipe/package yang di-refer tanpa `use` — jadi
    // tidak ada kode valid yang bisa "bocor" lewat pelebaran ini.
    for imp in file_scope_imports(file) {
        out.push_str(&imp);
        out.push('\n');
    }
    // Typedef yang DITULIS di dalam badan module tapi dipakai di ANSI port
    // list module yang sama (`module m { type Word8 = logic[7:0]  out v : Word8 }`)
    // harus berada di scope yang sama dengan port list — yaitu FILE, bukan
    // body. Kalau tetap di body, `output Word8 v` tidak ter-resolve
    // (verilator: "Cannot find file containing interface: 'Word8'").
    // Urutan: import dulu (bisa jadi tipe merujuk `use pkg::*`), lalu typedef.
    for td in file_scope_typedefs(file) {
        defs::emit_typedef(&mut out, 0, td);
    }

    for m in &file.modules {
        out.push('\n');
        module::emit_module_kw(&mut out, m, "module", iface_names);
    }
    // `program name { ... }` (MIVON-HDL.md §7.3) — testbench program
    for p in &file.programs {
        out.push('\n');
        module::emit_module_kw(&mut out, p, "program", iface_names);
    }
    for c in &file.classes {
        out.push('\n');
        defs::emit_class(&mut out, c);
    }
    for f in &file.funcs {
        out.push('\n');
        module::emit_func(&mut out, f);
    }
    for t in &file.tasks {
        out.push('\n');
        module::emit_task(&mut out, t);
    }
    out
}

// ── Helpers ──

/// Uniquifier label blok `generate` per module/program.
///
/// Dua blok generate dengan label sama di module yang sama itu ERROR LRM
/// 1800 §27.6 (hierarchical scope bentrok) —iverilog & verilator menolak.
/// Emitter lama memakai `gen_{var}` / `gen_cond` / `gen_cond_else` apa adanya,
/// jadi dua `for i in 0..N` dengan nama variabel sama (atau dua `if` generate)
/// menabrakkan label. Di sini nama yang sudah terpakai diberi sufiks `_1`,
/// `_2`, … secara deterministik (prinsip desain #2: byte-identik tiap run).
pub(crate) struct GenLabels {
    used: Vec<String>,
}

impl GenLabels {
    pub(crate) fn new() -> Self {
        Self { used: Vec::new() }
    }

    /// Kembalikan nama label unik berdasar `base` (sudah pasti unik bila
    /// `base` belum terpakai — kasus umum, tanpa sufiks).
    pub(crate) fn uniq(&mut self, base: &str) -> String {
        let mut cand = base.to_string();
        let mut n = 1usize;
        while self.used.contains(&cand) {
            cand = format!("{base}_{n}");
            n += 1;
        }
        self.used.push(cand.clone());
        cand
    }
}

/// Kumpulkan `import` yang harus di-emit di SCOPE FILE untuk semua
/// `use pkg::*` / `use pkg::item` yang muncul di module & program file ini.
///
/// Dedup per pasangan `(pkg, item)` supaya dua module yang memakai package
/// sama tidak mengulang import (LRM 1800 §26.3: meng-impor identifier yang
/// sama ke scope yang sama dua kali adalah error). Preserve urutan kemunculan
/// agar output deterministik (prinsip desain #2).
fn file_scope_imports(file: &MvFile) -> Vec<String> {
    let mut seen: Vec<(String, String)> = Vec::new();
    let mut out: Vec<String> = Vec::new();
    let units = file.modules.iter().chain(file.programs.iter());
    for unit in units {
        for item in &unit.items {
            let MItem::Use { pkg, item } = item else {
                continue;
            };
            if seen.iter().any(|(p, i)| p == pkg && i == item) {
                continue;
            }
            seen.push((pkg.clone(), item.clone()));
            out.push(format!("import {pkg}::{item};"));
        }
    }
    out
}

/// Kumpulkan typedef yang ditulis di dalam badan module & program, supaya
/// bisa di-emit di SCOPE FILE sebelum deklarasi module (port list module
/// di-resolve di enclosing scope — LRM 1800 §23.2.1.2). Dedup per nama:
/// dua module yang mendeklarasikan typedef sama sudah ditolak E2007 di
/// level `.mv`, jadi duplikat di sini hanya mungkin dari satu module.
fn file_scope_typedefs(file: &MvFile) -> Vec<&Typedef> {
    let mut seen: Vec<&str> = Vec::new();
    let mut out: Vec<&Typedef> = Vec::new();
    for unit in file.modules.iter().chain(file.programs.iter()) {
        for item in &unit.items {
            let MItem::Typedef(td) = item else { continue };
            let name = match td {
                Typedef::Alias { name, .. }
                | Typedef::Struct { name, .. }
                | Typedef::Union { name, .. }
                | Typedef::Enum { name, .. } => name.as_str(),
            };
            if seen.contains(&name) {
                continue;
            }
            seen.push(name);
            out.push(td);
        }
    }
    out
}

pub(crate) fn line(out: &mut String, indent: usize, s: &str) {
    out.push_str(&"    ".repeat(indent));
    out.push_str(s);
    out.push('\n');
}

/// Tipe dengan padding agar kolom nama rapi (minimal 1 spasi).
pub(crate) fn pad_type(t: String) -> String {
    if t.len() < 6 {
        format!("{t}{}", " ".repeat(6 - t.len()))
    } else {
        format!("{t} ")
    }
}

/// Suffix inisialisasi deklarasi: `= expr` bila ada, kosong bila tidak.
pub(crate) fn emit_init(init: &Option<Expr>) -> String {
    init.as_ref()
        .map(|e| format!(" = {}", expr::emit_expr(e)))
        .unwrap_or_default()
}

/// Ekspresi increment loop `for`: `i + 1` (default) atau `i + <step>` bila
/// `step` diberikan (`for i in 0..N step 2`). Pemanggil menulis `{var} = {}`.
pub(crate) fn for_inc(var: &str, step: Option<&Expr>) -> String {
    match step {
        Some(s) => format!("{var} + {}", expr::emit_expr(s)),
        None => format!("{var} + 1"),
    }
}

/// Deklarasi signal multi-nama yang BENAR utk SV: tipe di-emit SEKALI,
/// nama dipisah koma, dims array SETELAH tiap nama:
/// `sig a, b : logic[8][4]` → `logic [7:0] a [0:3], b [0:3]`
/// (sebelumnya `logic [7:0] a [0:3], logic [7:0] b [0:3]` — SV INVALID,
/// tipe berulang per nama). Dipakai deklarasi `sig`/`reg`/`var` multi-nama.
pub(crate) fn emit_signal_decl_multi(ty: &MvType, names: &[String]) -> String {
    // F40: queue membungkus tipe luar — pecah dulu, `[$]` dirender per nama.
    let (ty, is_queue) = match ty {
        MvType::Queue(inner) => (inner.as_ref(), true),
        other => (other, false),
    };
    let mut dims: Vec<&Expr> = Vec::new();
    let mut elem = ty;
    while let MvType::Array(inner, ds) = elem {
        dims.extend(ds.iter());
        elem = inner;
    }
    let ty_s = expr::emit_type(elem);
    let name_parts: Vec<String> = names
        .iter()
        .map(|n| {
            let mut s = n.clone();
            for d in &dims {
                let nn = match d {
                    Expr::Int(v) => format!("{}", v.saturating_sub(1)),
                    other => format!("{} - 1", expr::emit_expr(other)),
                };
                s.push_str(&format!(" [0:{nn}]"));
            }
            if is_queue {
                s.push_str("[$]");
            }
            s
        })
        .collect();
    format!("{ty_s} {}", name_parts.join(", "))
}

/// Deklarasi net multi-nama yang BENAR utk SV (LRM 1800 §6.5/§10.2):
/// net adalah tipe sendiri — TIDAK digabung dengan tipe variabel
/// (`wire bit w` INVALID, ditolak parser SV). Bentuk sah:
/// `wire w`, `wand [7:0] w`, `tri signed [7:0] w`, `wire Addr w` (typedef),
/// unpacked setelah nama (`wire [7:0] m [0:3]`).
/// F76: `net` = prefix resolution (`wire`/`wand`/`wor`/`tri`/...)
pub(crate) fn emit_wire_decl_multi(net: &str, ty: &MvType, names: &[String]) -> String {
    use crate::ast::{Expr, MvType};
    use expr::emit_expr;
    let mut dims: Vec<&Expr> = Vec::new();
    let mut elem = ty;
    while let MvType::Array(inner, ds) = elem {
        dims.extend(ds.iter());
        elem = inner;
    }
    // Packed range net: Bit → tanpa range, Logic(range) → range, Signed → signed+range.
    let packed = match elem {
        MvType::Bit => String::new(),
        MvType::Logic(None) => String::new(),
        MvType::Logic(Some((a, b))) => format!(" [{}:{}]", emit_expr(a), emit_expr(b)),
        MvType::Signed(inner) => match inner.as_ref() {
            MvType::Bit | MvType::Logic(None) => " signed".to_string(),
            MvType::Logic(Some((a, b))) => {
                format!(" signed [{}:{}]", emit_expr(a), emit_expr(b))
            }
            other => format!(" {}", expr::emit_type(other)),
        },
        MvType::Named(s, ..) => format!(" {s}"),
        other => format!(" {}", expr::emit_type(other)),
    };
    let name_parts: Vec<String> = names
        .iter()
        .map(|n| {
            let mut s = n.clone();
            for d in &dims {
                let nn = match d {
                    Expr::Int(v) => format!("{}", v.saturating_sub(1)),
                    other => format!("{} - 1", emit_expr(other)),
                };
                s.push_str(&format!(" [0:{nn}]"));
            }
            s
        })
        .collect();
    format!("{net}{packed} {}", name_parts.join(", "))
}
/// Deklarasi signal array unpacked yang BENAR utk SV:
/// `logic[8][4]` → `logic [7:0] name [0:3]` (dims `[0:N-1]` SETELAH nama,
/// bukan `logic [7:0] [4] name` yang di-parse SV sbg packed multi-dim).
pub(crate) fn emit_signal_decl(ty: &MvType, name: &str) -> String {
    // F40: queue — `[$]` SETELAH nama (bukan setelah tipe).
    let (ty, is_queue) = match ty {
        MvType::Queue(inner) => (inner.as_ref(), true),
        other => (other, false),
    };
    let mut dims: Vec<&Expr> = Vec::new();
    let mut elem = ty;
    while let MvType::Array(inner, ds) = elem {
        dims.extend(ds.iter());
        elem = inner;
    }
    let mut s = format!("{} {name}", expr::emit_type(elem));
    for d in dims {
        let n = match d {
            Expr::Int(v) => format!("{}", v.saturating_sub(1)),
            other => format!("{} - 1", expr::emit_expr(other)),
        };
        s.push_str(&format!(" [0:{n}]"));
    }
    if is_queue {
        s.push_str("[$]");
    }
    s
}
