// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : defs.mvh
// Perintah  : mivon mgen defs.mvh
// ─────────────────────────────────────────────────────────────

`ifndef DEFS_SVH
`define DEFS_SVH

typedef logic [15:0] Addr;

package mvh_pkg;
    typedef enum logic [1:0] { IDLE, RUN, DONE } State;
    localparam MAX_CNT = 15;
endpackage

`endif
