// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : dut.mv
// Perintah  : mivon mgen dut.mv
// ─────────────────────────────────────────────────────────────

import mvh_pkg::*;

module upcounter (
    input  bit clk,
    input  bit rst_n,
    input  bit enable,
    output Addr count = '0,
    output State state = IDLE
);

    // ── logika sekuensial ──
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            count <= '0;
            state <= IDLE;
        end else if (state == DONE) begin
            state <= IDLE;
            count <= '0;
        end else if (enable) begin
            state <= RUN;
            if (count == MAX_CNT - 1) begin
                count <= '0;
                state <= DONE;
            end else begin
                count <= count + 1;
            end
        end
    end
endmodule
