// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : tb.mv
// Perintah  : mivon mgen tb.mv
// ─────────────────────────────────────────────────────────────

`include "defs.svh"
import mvh_pkg::*;

module tb_mvh;
    bit clk;
    bit rst_n;
    bit enable;
    Addr count;
    State state;
    bit done;

    upcounter u_cnt (
        .clk    (clk),
        .rst_n  (rst_n),
        .enable (enable),
        .count  (count),
        .state  (state)
    );

    // ── initial ──
    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end

    // ── initial ──
    initial begin
        rst_n = 0;
        enable = 0;
        #20 rst_n = 1;
        enable = 1;
        repeat (16) @(posedge clk) ;
        if (state == DONE && count == 0) begin
            $display("TB_MVH_OK count=%0d state=%0d", count, state);
            done = 1;
        end else begin
            $display("TB_MVH_BROKEN count=%0d state=%0d", count, state);
        end
        $finish;
    end
endmodule
