// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : tb.mv
// Perintah  : mivon mgen tb.mv
// ─────────────────────────────────────────────────────────────

`include "types.svh"
import chip_types::*;

module tb_mem;
    mem_if bus();
    bit rst_n;
    State st;
    Addr addr;
    bit done;

    memory_dut u_dut (
        .axi   (bus),
        .rst_n (rst_n),
        .st    (st),
        .addr  (addr)
    );

    // ── initial ──
    initial begin
        while (1) begin
            bus.clk = 0;
            #5 bus.clk = 1;
            #5;
        end
    end

    // ── initial ──
    initial begin
        rst_n = 0;
        #30 rst_n = 1;
        bus.we = 1;
        bus.addr = 16'h10;
        bus.din = 32'hcafe;
        #60 begin
            if (addr == 16'h6 && st == WR) begin
                $display("TB_MF_OK addr=%0d st=%0d", addr, st);
                done = 1;
            end else begin
                $display("TB_MF_BROKEN addr=%0d st=%0d", addr, st);
            end
        end
        $finish;
    end
endmodule
