// ─────────────────────────────────────────────────────────────
// Generated by mivon mgen — DO NOT EDIT
// Sumber    : my_test.mv
// Perintah  : mivon mgen my_test.mv
// ─────────────────────────────────────────────────────────────


class my_test extends uvm_test;
    logic [31:0] count;
    rand logic [31:0] seed;

    constraint c {
        seed > 10;
        seed < 200;
    }

    function new(input string name);
        super.new(name);
    endfunction

    function void build_phase();
        uvm_config_db::set(this, "*.agent", "count", count);
    endfunction

    task run_phase();
        uvm_sequencer seqr;
        uvm_sequence_item item;
        seqr.start_item(item);
        seqr.finish_item(item);
        #100;
    endtask
endclass
